services:
  - type: web
    name: volleyball-bot
    env: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: POSTGRES_DSN
        sync: false